# Generated by Django 4.0.7 on 2022-08-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Date",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Jurisdiction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name="Statute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=2048)),
                ("summary", models.TextField()),
                ("date", models.DateField(null=True)),
                (
                    "jurisdictions",
                    models.ManyToManyField(
                        related_name="statutes", to="firearms.jurisdiction"
                    ),
                ),
                (
                    "related_dates",
                    models.ManyToManyField(related_name="statutes", to="firearms.date"),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        related_name="statutes", to="firearms.subject"
                    ),
                ),
            ],
        ),
    ]
