# Generated by Django 4.0.7 on 2022-08-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_id', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('cast', models.TextField()),
                ('country', models.CharField(max_length=25)),
                ('date_added', models.DateField()),
                ('release_year', models.DateField()),
                ('rating', models.CharField(max_length=15)),
                ('duration', models.CharField(max_length=100)),
                ('listed_in', models.TextField()),
            ],
        ),
    ]
