# Generated by Django 4.0.7 on 2022-08-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0002_film_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="country",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="film",
            name="duration",
            field=models.CharField(max_length=1000),
        ),
    ]
