# Generated by Django 4.0.7 on 2022-09-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0004_alter_film_director_alter_film_show_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name="film",
            name="genres",
            field=models.ManyToManyField(to="films.genre"),
        ),
    ]
